//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb2.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.EncabezadoFactura = new HashSet<EncabezadoFactura>();
        }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese un NIT")]
        public string NIT { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese el nombre del cliente")]
        public string nombreCliente { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese el apellido del cliente")]
        public string apellidoCliente { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese el télefono")]
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncabezadoFactura> EncabezadoFactura { get; set; }
    }
}
