//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb2.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiales()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int codigoMaterial { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese el material")]
        public string nombreMaterial { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese el detalle del material")]
        public string detalleMaterial { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ingrese el precio del material")]
        public string precioMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
    }
}
